name: zymixx_todo_list
description: "windows todo list"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-279.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  drift: ^2.14.1
  flutter_bloc: ^8.1.3
  get: ^4.6.6
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18
  window_manager: ^0.3.7
  keyboard_event: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  source_gen: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - images/