name: zymixx_todo_list
description: "windows todo list"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-279.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  flutter_localization: 0.2.0
  drift: ^2.14.1
  flutter_bloc: ^8.1.3
  get: ^4.6.6
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18
  window_manager: ^0.3.7
  keyboard_event: ^0.3.4
  intl: ^0.19.0
  audioplayers: ^5.2.1
  logger: ^1.4.0
  syncfusion_flutter_datepicker: 24.2.6
  gap: ^3.0.1
  fl_chart: ^0.67.0
  file_picker: ^8.0.0+1
  watcher: ^1.1.0
  flutter_fortune_wheel: ^1.3.1
  system_tray: ^2.0.3
  confetti: ^0.7.0
  reorderable_grid: ^1.0.10
  screen_retriever: ^0.1.9
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.0
  flame: ^1.15.0
  flame_forge2d: ^0.16.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  source_gen: ^1.5.0
  mockito: ^5.0.17
  integration_test:
    sdk: flutter
  audioplayers: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/imready256Ñ…256.ico
    - assets/songs/
    - assets/git_gif/
  fonts:
      - family: Consolas
        fonts:
          - asset: assets/fonts/consolas.ttf
